admin_user_homepage:
    path:     /users
    defaults: { _controller: AdminUserBundle:User:index }
    
admin_user_data:
    path:     /users/data/{id}
    defaults: { _controller: AdminUserBundle:User:data, id:0 }

admin_user_save:
    path:     /users/save
    defaults: { _controller: AdminUserBundle:User:save }

admin_user_delete:
    path:     /users/delete
    defaults: { _controller: AdminUserBundle:User:delete }